#!/usr/bin/env sh

if [ -z "${SERVICE_FQDN}" ]; then
    echo "[ERROR] SERVICE_FQDN is not set"
    exit 1
fi

cat << EOF
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world-app-ingress
spec:
  rules:
  - host: ${SERVICE_FQDN}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-world-app-service
            port:
              number: http-port
EOF
